config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments, :only => [:update, :destroy, :post]
  end

  post 'posts/:post_id/comments/:id' => 'comments#create'
  get 'get_login'   => 'users#get_login'
  post 'get_login'   => 'users#login'
  get 'logout'   => 'users#logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # validates :content, :user_id, :post_id, presence: true
end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # validates :user_id, :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :downvotes
  has_many :upvotes
  belongs_to :user

  # validates :title, :content, :user_id, presence: true
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # validates :user_id, :post_id, presence: true
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_many :posts
  has_many :comments
  has_many :downvotes
  has_many :upvotes

  # validates :username, :password, presence: true

  has_secure_password

  # def password
  #   BCrypt::Password.new(hashed_password)
  # end
  #
  # def password=(new_password)
  #   self.hashed_password = BCrypt::Password.create(new_password)
  # end
  #
  # def self.authenticate(username, password)
  #   user = User.find_by(username: username)
  #   if user.password == password
  #     user
  #   else
  #     nil
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
     @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
  end

  def update
  end

  def destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render 'new'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to '/login'
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def get_login
    render 'get_login'
  end

  def login
    user = User.find_by(username: params[:user][:username].downcase)
    user.authenticate(params[:user][:password])
    if user != nil
      session[:user_id] = user.id
      redirect_to '/'
    else
      @error = "The credentials you provided didn't match our records. Please try again."
      render '/get_login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to "/"
  end

  def show
    if current_user
      @user = User.find(params[:id])
      render 'show'
    else
      redirect_to '/'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit Jr.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to 'Home', root_path %>

  <% if current_user %>
    <%= link_to 'Submit New Post', new_post_path %>
    <%= link_to 'Logout', logout_path %>
  <% else %>
    <%= link_to 'Login', get_login_path %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Latest Posts</h1>
  <% @posts.each do |post| %>
    <h3><%= link_to post.title, post_path(post) %></h3>
    <p>karma <%= post.karma %></p>
    <%= link_to 'Comments', post_path(post) %>
    <br>
  <% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
  <p>Submitted by <%= @post.user.username %> </p> <!-- make username a link to user show page -->
  <h4><%= @post.content %></h4>
  <p>karma <%= @post.karma %></p>
  <br>
  <p>comments:</p>
    <% @post.comments.each do |comments|%>
      <%= comments.content %>
    <% end %>

app/views/users/get_login.html.erb
<%= form_for :user, url: get_login_path do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit "Login" %>
  </p>
<% end %>